### ISSUE TITLE
All case study pages render title incorrectly

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-content#108]
![image](https://user-images.githubusercontent.com/1566470/49468451-c6bbb180-f7b9-11e8-8acd-82d873455da2.png)

**Comment by mpennie** [comment]
Thank you for fixing it -- Also, the submit box formatting is crowded with too much text.

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/49521619-8853ee80-f8ae-11e8-9597-3db922a10ced.png)
Done

**Comment by Woland2k** [comment]
Bosch case study has proffs as a background:

![image](https://user-images.githubusercontent.com/1566470/49531157-866a3b00-f86e-11e8-90e2-f2a0cd3669d2.png)

**Comment by Woland2k** [comment]
@tatarincev still not fully fixed

**Comment by tatarincev** [comment]
Done https://staging.virtocommerce.com/case-studies/bosch

**Comment by Woland2k** [comment]
Still wrong, background image is proffs not bosch

**Comment by tatarincev** [comment]
Try to reset  browser cache

**Comment by Woland2k** [comment]
I did, i disabled caching and tried opening in the different browser. Still the same old background. Post the screenshot of what you see.

**Comment by tatarincev** [comment]
https://user-images.githubusercontent.com/7566324/48930344-91c97800-eef8-11e8-999a-6f37a060bd64.png

**Comment by Woland2k** [comment]
Ok, i see it in production site, the URL above was for staging which still had old image.
